# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa01a067618dfc8386ea7d63ec8bb2c8476b30e6a00d3057799ad66fd68c0352610f354b8a7cc4695ee058033db504032145e67db0c60013e952e6fbe1ead62

test:
  secret_key_base: c7b78214f5b6703966839d6e127be445a8b7fc5801f1abace81332eafeece8cda9e693fabc51acf7d7771a80d175443ec55be323b701da37e8ba58f1988c08c7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
